apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: finalizers
spec:
  version: {{ .TagName }}
  homepage: https://github.com/ibuildthecloud/finalizers
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/ibuildthecloud/finalizers/releases/download/{{ .TagName }}/finalizers_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-finalizers
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/ibuildthecloud/finalizers/releases/download/{{ .TagName }}/finalizers_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-finalizers
  shortDescription: List objects blocked by finalizers.
  description: |
    List objects blocked by finalizers.
